Yet more improvements
This can now correctly extract all sequences from the genome, check that
the right sequences were found and then run searches. This requires lots
of changes, including this like removing entries where the range and
sequence do not match as well as lots of other issues.

diff --git a/bin/pombe b/bin/pombe
--- a/bin/pombe
+++ b/bin/pombe
@@ -8,6 +8,10 @@ fetch() {
   curl "$1" 2>/dev/null | gzip -d
 }
 
+getfasta() {
+  bedtools getfasta -split -name -s -fi "$1" -bed "$2" | sed 's/::/ /'
+}
+
 base="$PWD/data/pombe/"
 remote_genome="ftp://ftp.ensemblgenomes.org/pub/current/fungi/fasta/schizosaccharomyces_pombe/dna/Schizosaccharomyces_pombe.ASM294v2.dna.toplevel.fa.gz"
 extra_genome="ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Chromosome_Dumps/fasta/Schizosaccharomyces_pombe.ASM294v2.30.dna.genome.fa.gz"
@@ -33,34 +37,47 @@ summary="$base/summary.csv"
 tmp="$(mktemp -d)"
 pushd "$tmp"
 
-cat >bad-silva <<EOF
-URS000055C986
-URS00002B25BC
-URS000017889A
-URS00001C5837
-EOF
-
 echo 1>&2 'Fetching remote data'
 
-cat 1>&2 <<EOF
-This is excluding extracting and hasing from silva that have known issues.
-Notably the sequences from silva are too short, often. This leads to the ranges
-in the bed file being wrong. And since the range is wrong the extracted
-sequences and then hashes are wrong. Excluding:
-EOF
-cat bad-silva
-
-fetch "$remote_bed" | correct-bed.py - - | grep -vf bad-silva > $bed
+fetch "$remote_bed" | correct-bed.py - $bed
 fetch "$remote_known" > "$known"
 fetch "$remote_genome" > "$genome"
 fetch "$extra_genome" > "$extra"
-fetch "$remote_md5s" > "$md5s"
+
+echo 1>&2 "Finding troublesome silva/URS0000156566 entries"
+grep 'silva' "$known" | gff2bed.py - silva.bed
+grep 'URS0000156566' "$known" | gff2bed.py - - >> silva.bed
+getfasta "$genome" silva.bed > silva.fasta
+grep '^>' silva.fasta | cut -d ' ' -f1 | tr -d '>' > bad-silva
+
+fetch "$remote_md5s" | grep -vf bad-silva > "$md5s"
+
+echo 1>&2 "Determining UPI's missnig from BED file but in gff"
+cut -f4 "$bed" | sort -u > bed.upi
+cut -f9 "$known" | tr ';' '\n' | awk -F '=' '{ if ($1 == "Name") print $2 }' | sort -u > gff.upi
+comm -1 -3 bed.upi gff.upi | grep -vf bad-silva > bed-missing.upi
+
+echo 1>&2 "Missing $(wc -l bed-missing.upi) entries from bed"
+echo 1>&2 "Appending missing to gff"
+grep -f bed-missing.upi "$known" | gff2bed.py - extra.bed
+
+echo 1>&2 "Added $(wc -l extra.bed) entries"
+cat extra.bed >> "$bed"
 
 echo 1>&2 'Extracting targets'
-bedtools getfasta -split -name -s -fi "$genome" -bed "$bed" | sed 's/::/ /' > "$targets"
+getfasta "$genome" "$bed" > "$targets"
 
-# echo 1>&2 'Checking MD5 sums'
-# md5sum -c "$sums"
+cat 1>&2 <<EOF
+Ignoring MD5 hashes for silva sequences. As the sequence extracted from the
+given range and the given sequence one differ leading to the the computed
+hashes will differ. This means that we will fail the hash check because we
+assign the same UPI to different sequences in the case of silva. The ranges are
+correct, while the given sequences are not, thus we ignore the computed hashes
+in this case.
+EOF
+
+echo 1>&2 'Checking MD5 sums'
+md5sum -c "$sums"
 
 echo 1>&2 'Validating sequence hashes'
 fasta.py md5 display $targets computed.tsv
@@ -71,20 +88,12 @@ cat bad-md5
 [ -s bad-md5 ] && exit 1
 echo 1>&2 'All hashes pass'
 
-echo 'Manually adding the excluded sequences back to the target file'
-cat >>"$targets" <<EOF
->URS00001C5837 MT:3,147-4,523:1
-ATAAAAATATATATAATGAGTTTGATGTTAGCTCGGTTATAACGCTATCTAGAGATTTTAACACATGCAAATCGAACGAATCAACAAAAACAATACATCCTTTAGGGGATGTTTGTGTTTTTTTGTGACGTGGTGAACAGGTGAGTAAAAGGGAAGAACGGACCTTAAATTTCGGCTAAATTCCGAATAAACACACTCTTTTGGAGTGTTGTGAAAGAAGTGAAAACTTTGATTTAAGACTGGCTTCTTACGATTAAAGTAGTTGGAGAGGTAAAAGCTTAACAAGCTCAAATCGTAATCATGACACTAAGTGGTGCTCTGATCACATTGGCTCTGAGACAACAGCCAAGATGAACATTTAGTTCATCCAGCAGTGGAGAATATTAGTCAATGATCGAAAGATTGAACTAGTCATCTAGAAGAGTGAAACTTTTAGTTATAGCTCCTTAAATTAAGAAAATTTGATTCTTAATTTTATGTAATTCTTGCCAATTTCCGTGCCAGCAGCAGCGGTTATACGGATAGAATAAGCGTTTAACATAATAAAAAGGCCTAAAAAGTATGTAGATGGAAAAAAACAAATCTTTTTCTAGAGTAATAAAGATGTTTGTAGTATTGTCAAATAAGGGATCAAATCCGACAATCTTGATGAGACTGCTTAAGTAAAAACTACTTACAATTAATTACTGACATTGAGATACGAAGGCTTAGATCGCGAAAGAGATTAGATACCTCTGTAGTCTAAGCTGTAAACGATTATTGCTCTCCCAATCTTTTTGATTGGGTTTAGTGAAGACGGTAAGCAATATGCCTGGGGAGTACTTTCGCAAGATTGAAACCCAAAACATTAGACGGTCTTGGAAATCCGCAGTGAATCATGTTATTTAATTAGATAATCCGCTAAAAATCTTACCTTTCCTTAAAACAATTAGTTTTAATTGTTGGGTATTGCATGGCTGTCTTTAGTTAATCTCGTAAGATGAGGTTAATTCCCATTAATTAACGAAAGCCTTCAAAGAATTTGTTTTTCTTTGTGTTAGTGATAAGCTAACTTTTTAGAGGGTTAAGACAAGTCAATATGATCCTTATGGAAAGGGCTATAGACGTGATATAAAATCTAATCCAATAATTTTTAATATCGAAAGATTGAAGTATTATTATAATGGTTAGGAGATTTATTCAGATTTAAATCTGTAATTTGATTTAATGAAGGAGGAATTGCGAGTAATCACTAATCATTACGTAGTGGTGAAATTTATCTCTGAGATGTACTAACTACTCGTCAAGCGCTGAAAGTATTAATCTCTTGAAGAAGACATTCATTTGTTTTCCCAAGGTGTTGTGCAATTAGTGTTAAGTCGAAATAAGGTAACCGTAGTGGAAGTTGCGGTTGAACTAATTAATTCAGGTTAACCCCCCCCC
->URS00002B25BC III:2,451,883-2,452,883:1
-TACCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCAATTTTGTACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATCGTTTATTTGATAGTACCTCAACTACTTGGATAACCGTGGTAATTCTAGAGCTAATACATGCTAAAAATCCCGACTTTTTTGGAAGGGATGTATTTATTAGATAAAAAACCAATGCCTTCGGGCTTTTTTTGGTGAGTCATAATAACTTTTCGAATCGCATGGCCTTGCGCCGGCGATGGTTCATTCAAATTTCTGCCCTATCAACTTTCGATGGTAGGATAGAGGCCTACCATGGTTTTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATAACAATGCAGGGCCCTTTCGGGTCTTGTAATTGGAATGAGTACAATGTAAATACCTTAACGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGAACTTTGAGCCTGGTCGACTGGTCCGCCGCAAGGCGTGTTTACTGGTCATGACCGGGGTCGTTAACCTTCTGGCAAACTACTCATGTTCTTTATTGAGCGTGGTAGGGAACCAGGACTTTTACCTTGAAAAAATTAGAGTGTTCAAAGCAGGCAAGTTTTGCTCGAATACATTAGCATGGAATAATAAAATAGGACGTGTGGTTCTATTTTGTTGGTTTCTAGGACCGCCGTAATGATTAATAGGGATAGTCGGGGGCATTCGTATTCAATTGTCAGAGGTGAAATTCTTGGATTTATTGAAGACGAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGAAAGTTAGGG
-> URS000055C986
-TACCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCAATTTTGTACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATCGTTTATTTGATAGTACCTCAACTACTTGGATAACCGTGGTAATTCTAGAGCTAATACATGCTAAAAATCCCGACTTTTTTGGAAGGGATGTATTTATTAGATAAAAAACCAATGCCTTCGGGCTTTTTTTGGTGAGTCATAATAACTTTTCGAATCGCATGGCCTTGCGCCGGCGATGGTTCATTCAAATTTCTGCCCTATCAACTTTCGATGGTAGGATAGAGGCCTACCATGGTTTTAACGGGTAACGGGGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAAGAAATAACAATGCAGGGCCCTTTCGGGTCTTGTAATTGGAATGAGTACAATGTAAATACCTTAACGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGAACTTTGAGCCTGGTCGACTGGTCCGCCGCAAGGCGTGTTTACTGGTCATGACCGGGGTCGTTAACCTTCTGGCAAACTACTCATGTTCTTTATTGAGCGTGGTAGGGAACCAGGACTTTTACCTTGAAAAAATTAGAGTGTTCAAAGCAGGCAAGTTTTGCTCGAATACATTAGCATGGAATAATAAAATAGGACGTGTGGTTCTATTTTGTTGGTTTCTAGGACCGCCGTAATGATTAATAGGGATAGTCGGGGGCATTCGTATTCAATTGTCAGAGGTGAAATTCTTGGATTTATTGAAGACGAACTACTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGAAAGTTAGGGGATCGAAGACGATCAGATACCGTCGTAGTCTTAACCATAAACTATGCCGACTAGGGATCGGGCAATGTTTCATTTATCGACTTGCTCGGCACCTTACGAGAAATCAAAGTCTTTGGGTTCCGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACAATGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAACTCACCAGGTCCAGACATAGTAAGGATTGACAGATTGAGAGCTCTTTCTTGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGCTTAATTGCGATAACGAACGAGACCTTAACCTGCTAAATAGCTGGATCAGCCATTTTGGCTGATCATTAGCTTCTTAGAGGGACTATTGGCATAAAGCCAATGGAAGTTTGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACGGAGCCAACGAGTTGAAAAAAATCTTTTGATTTTTTATCCTTGGCCGGAAGGTCTGGGTAATCTTGTTAAACTCCGTCGTGCTGGGGATAGAGCATTGCAATTATTGCTCTTCAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGAATACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGCTTAGTGAGGCCTCTGGATTGGCTTGTTTCTGCTGGCAACGGCGGAAACATTGCCGAGAAGTTGGACAAACTTGGTCATTTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA
->URS000017889A MT:34-2,760:1
-AATGTGTAATTTGAATCAATTTCTATCCTTTTAAAAATACATCATAAAGTGTACTTTTTTAAGGATTTAGTTATTAAAGGATTAATTATGGATTGCTAACCAGTTAATATTAAGAGGAAGCTTTTAAAGCTTAATTCAGCAATTTTTTAATTGTTGTTTCTCCTAAAGGTAAACCACTAAAAAGAAAGAACTTCGGGTTTTTCTTTAAAATAAACTAGAGGAACTGAATCATCTTAGTACTCTAAGGAAAATAAAATAACAATGATTATTGTAGTAGTGGCGAACGAATCATTAATAGTCTAACTTATAAAAATATTAAAAAAAATTTTTACCAAAGAAGAGAAAAATGGGTTCTTCATTTTTAATAAGTAATAAGTAATAAAGTAAAATGGGAACTTAACCTGTTTGAATATTGGAGAACCAATCTCCAAAGACTAAATATATTAACTGAGTGATAGTGAAGAGTACCGTAAGGGAAAGCAATGAAATAGTTAATCTATAAGCGAAGATAGTGAATTTTAAATAAATTATTATCTTGTACCTTTTGCATAATGGGTCAGCAAGTTTTAATTATTTGCAAGCTGAAAAGCCATAAAGTAAATAATTAAAGACCCGAAACCTGACGATCTTACCATGAACAGATTTTAAGGATCGAACCAGTAATCGTTGCAAAGATTTTGGATGATTTGTGGTAAGGGGTGAAATGCTAATCGAGTTAGGTGATAGCTGGTTGTCCACGAAACCATTTTAAGATGGGCACTTCAAAAACTAAATGAGGTACAGAAATTTATTGCCTTCAAGAAGTTTTTTCTTGTTAATAGGGGATCTAAAGATTTACCTAAGGCGTTAATTAATCTCGGAATAAATTTAAAAAAGTTTGAAGTAGTTAGACAATTGGCGATAAGGTCAATAGTCAAAAGAGAAACAGCTCAGATCAAAGATTTAAAGTTCCCCAATTTAAGTTAAGTGATTTAAAGATAGTCTTACTCCTTATTCAATAAGAATATGGGCTTGGAAACAGCCATTATCTAAGGAGTACGTAATAGTTCACTTATCCAAAAAAAATAATATTTTCTGGAGAAAGGCATCAAAAATTTAACGGATCTTAAACTTAATACTTAAACTTTGGCAGTATTTTAAAAATACTGGGTAGTGGACCGATCTATATAAAGATGAAGATGAACTTTTAAGTTTATTGGATTTATTAGATGCGAGAATGCTGACATAAGTAACGTAAAAAAAGGTCAAATTCCTTTTCACCGAAAACTGAAGGGTTTTGACTTAAAAAGCTTAGCTTAAGTCAAATAAAGTAACAATCTCTAAGCTAATAAATAGTGATGAGTAAATCTTAACGGATCTTAAAATAAAAGTTTTATTGAATAGAAATTTTTATTCAGGAAAATTATCCGTTATTTTAATTGTACCCTAAACCGACACTGGTCAGTTAAGAGAATATCTTAAGGTGTTGAGAGAACTATGCTTAAGGAACTCGGCAAATTAGCTCTGTTACTTCGGTATAAAGAGTGTTCATTATTTTATGAACTCAATAAAGAGAACCCTACAACTGTTTACTTAAAACACAGCACATTGCCAAAATTAAAAAATTATAGTATAATGTGTGAGGTCTGCTCAATGTCCTATGGTTAACAATACGAACTTTAACGAGTTTTACGGAACCCAGGATAAATAGCGGCTTTAACTCTGAGGGTCCTAAGGTAGCGAAATTCCTTGTCCGATAAATACGGTCCCGCATGAATGACTTAATGATAGGGTTGCTGTCTCAAGCACAGACTCAGTGAAATTGTAATTGCTGTGAAGATACAGTGTTCCCTCAGCTAGACGGAAAGACCCTGGCAGCTTTACGATAGTTAATTATTGATTAAAGAAAAAATCATCCAAAAGGTGATCTCTTCTTTCTCGCTTTATCTATTTTTGTTCAGTATAGAGGTTAGTCGTTTAGACAAAAATGAGATATCCTCCTTAAATAATAAAGATCTTTAAAGTTTAAACTTGACATTAATTAATTGATCGTTTCTGTGGGGCGCAGGCCTCATAAAAAATAACTGAGGTATCCTAGATCTATATAATTTATCTAGAAATCAAAGTATCCAGAAACATTTTTTAAGTGTTTCTTAATTAAAGATACATGACGCATATAAGCATAAATAGGTTAAACTGAAAGACTAACAAGTCGCACAGATATGTAAATAGGGTTAAATGATCCACATTGAAACACTAATTTAGTGTTTGTATGGAAAACAATGTGCTCAATGAGCGAAGTTACGCCAGGGATAACAGGTTAATAGAGAGCTAAAGTACAAATCAAATTCTCTGTTTGACACCTCGATGTCGACTCAACCTATCTCCGGTTGTAGCAGATTGGAAGGGTTAGACTGTTCGTCTATTTAAAAGGTTACGTGAGTTGGGTTAAATCCGTCGTAAGACAGGATGGTTCCTATCTACTGAGGGAAAAATAAGCAAATTAAAATTTATCTTTTGTACGCAAGGATTTAGATAATTCAATCTCTAGTTTAACTATTGTTACTTAAATAAAAGTACTTTATTCAAAAGTTAAAAATTAAGTAGCACGGTAGTAAAGCCAAATTGAACAAATTAAAAACTGAAAGCATCTCAAGTTTGAAATTTATTTAAAGAGCTTATATTAAGAAAGTAGAAAACTTTCCAAAAGGACATCCTTAGGATGTACAAATCCTTATTTTAGTAAATCATTGTTTAGATAGATTTAGTTAATTTTTTAACCAAAGGGATTATCTCTTTGCTAATTTTTTAAATAACTGGAAATTGCCTAATTACACAATTTT
-EOF
-
 echo 'Altering targets to RNA'
 fasta.py dna-to-rna "$targets" t
+mv t "$targets"
+
+echo 'Limiting targets to only unique entries'
+fasta.py merge-by-id "$targets" t
 mv t "$targets"
 
 cp "$bed" "$known" "$genome" "$targets" "$base"
@@ -106,6 +115,6 @@ echo 1>&2 'Comparing to known locations'
 gm.py hits compare "$selected" "$known" "$compared"
 
 echo 1>&2 'Writing gff file from comparisions'
-gm.py as "$compared" gff "$gff"
+gm.py as gff "$compared" "$gff"
 
 gm.py comparisions summary "$compared" - | tee "$summary" | xsv table
