Rework to a Makefile approach
This now can do the pombe mapping using the Makefile. This should be
easy to extend to a new organism like C. elegans. I also reduce the
amount of stuff in the repo so this is easier to clone. This probably
makes it less reproducible as it is possible that the genomes and such
will change without our knowing.

diff --git a/bin/targets-bed b/bin/targets-bed
--- a/bin/targets-bed
+++ b/bin/targets-bed
@@ -1,7 +1,28 @@
-#!/usr/bin/env
+#!/usr/bin/env bash
 
 set -euo pipefail
 IFS=$'\n\t'
+BIN=$(dirname $0)
 
+raw=$1
+known=$2
+bad_ids=$3
 
-bin/missing-from-bed data/celegans/known.bed data/celegans/known.gff3
+bed_upi=$(mktemp)
+gff_upi=$(mktemp)
+ignored=$(mktemp)
+missing=$(mktemp)
+extra=$(mktemp)
+
+$BIN/ignored-ids $known $bad_ids > "$ignored"
+cut -f4 "$raw" | sort -u > $bed_upi
+$BIN/upi-from-gff $known > $gff_upi
+
+comm -1 -3 $bed_upi $gff_upi | grep -vf "$ignored" > $missing
+
+echo 1>&2 "Missing $(wc -l $missing | cut -d ' ' -f1) UPI's from bed"
+grep -f $missing "$known" | $BIN/gff2bed.py - $extra
+
+echo 1>&2 "Added $(wc -l $extra | cut -d ' ' -f1) entries"
+cat $raw
+cat $extra
